-- Create "payments" table
CREATE TABLE "payments" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY ("id"));
-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "mobile" character varying NOT NULL, "password" character varying NOT NULL, "firstname" character varying NULL, "lastname" character varying NULL, "national_code" character varying NULL, "active" boolean NOT NULL DEFAULT true, "deleted" boolean NOT NULL DEFAULT false, "address" text NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, PRIMARY KEY ("id"));
-- Create index "user_id" to table: "users"
CREATE UNIQUE INDEX "user_id" ON "users" ("id");
-- Create index "users_mobile_key" to table: "users"
CREATE UNIQUE INDEX "users_mobile_key" ON "users" ("mobile");
-- Create "main_iots" table
CREATE TABLE "main_iots" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "display_name" character varying NOT NULL, "lat" point NULL, "lon" point NULL, "address" text NULL, "serial_number" character varying NULL, "mac_address" character varying NULL, "ip_remote" character varying NULL, "status" character varying NULL, "active" boolean NOT NULL DEFAULT true, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "user_mainiots" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "main_iots_users_mainiots" FOREIGN KEY ("user_mainiots") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "device_iots" table
CREATE TABLE "device_iots" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "display_name" character varying NOT NULL, "serial_number" character varying NULL, "type_device" bigint NULL, "status" character varying NULL, "active" boolean NOT NULL DEFAULT true, "lat" point NULL, "lon" point NULL, "created_at" timestamp NOT NULL, "updated_at" timestamp NOT NULL, "main_iot_deviceiots" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "device_iots_main_iots_deviceiots" FOREIGN KEY ("main_iot_deviceiots") REFERENCES "main_iots" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "device_details" table
CREATE TABLE "device_details" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "light_status" boolean NULL, "device_iot_devicedetails" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "device_details_device_iots_devicedetails" FOREIGN KEY ("device_iot_devicedetails") REFERENCES "device_iots" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "roles" table
CREATE TABLE "roles" ("id" smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "description" character varying NULL, PRIMARY KEY ("id"));
-- Create index "role_id" to table: "roles"
CREATE UNIQUE INDEX "role_id" ON "roles" ("id");
-- Create index "roles_name_key" to table: "roles"
CREATE UNIQUE INDEX "roles_name_key" ON "roles" ("name");
-- Create "role_users" table
CREATE TABLE "role_users" ("role_id" smallint NOT NULL, "user_id" bigint NOT NULL, PRIMARY KEY ("role_id", "user_id"), CONSTRAINT "role_users_role_id" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "role_users_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create "plans" table
CREATE TABLE "plans" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL, "price" bigint NULL, "period" bigint NULL, "active" boolean NOT NULL DEFAULT true, "description" text NULL, PRIMARY KEY ("id"));
-- Create index "plans_name_key" to table: "plans"
CREATE UNIQUE INDEX "plans_name_key" ON "plans" ("name");
-- Create "user_payment_plans" table
CREATE TABLE "user_payment_plans" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "amount" bigint NULL, "reference_number" character varying NOT NULL, "transaction_number" character varying NULL, "source_account_number" character varying NULL, "destination_account_number" character varying NULL, "deleted" boolean NOT NULL DEFAULT false, "created_at" timestamp NOT NULL, "plan_userpaymentplans" bigint NOT NULL, "user_userpaymentplans" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "user_payment_plans_plans_userpaymentplans" FOREIGN KEY ("plan_userpaymentplans") REFERENCES "plans" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "user_payment_plans_users_userpaymentplans" FOREIGN KEY ("user_userpaymentplans") REFERENCES "users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
