// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"siliconvali/ent/devicedetails"
	"siliconvali/ent/deviceiot"
	"siliconvali/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeviceDetailsQuery is the builder for querying DeviceDetails entities.
type DeviceDetailsQuery struct {
	config
	ctx             *QueryContext
	order           []devicedetails.OrderOption
	inters          []Interceptor
	predicates      []predicate.DeviceDetails
	withDeviceiotID *DeviceIotQuery
	withFKs         bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeviceDetailsQuery builder.
func (ddq *DeviceDetailsQuery) Where(ps ...predicate.DeviceDetails) *DeviceDetailsQuery {
	ddq.predicates = append(ddq.predicates, ps...)
	return ddq
}

// Limit the number of records to be returned by this query.
func (ddq *DeviceDetailsQuery) Limit(limit int) *DeviceDetailsQuery {
	ddq.ctx.Limit = &limit
	return ddq
}

// Offset to start from.
func (ddq *DeviceDetailsQuery) Offset(offset int) *DeviceDetailsQuery {
	ddq.ctx.Offset = &offset
	return ddq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ddq *DeviceDetailsQuery) Unique(unique bool) *DeviceDetailsQuery {
	ddq.ctx.Unique = &unique
	return ddq
}

// Order specifies how the records should be ordered.
func (ddq *DeviceDetailsQuery) Order(o ...devicedetails.OrderOption) *DeviceDetailsQuery {
	ddq.order = append(ddq.order, o...)
	return ddq
}

// QueryDeviceiotID chains the current query on the "deviceiot_id" edge.
func (ddq *DeviceDetailsQuery) QueryDeviceiotID() *DeviceIotQuery {
	query := (&DeviceIotClient{config: ddq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ddq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ddq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(devicedetails.Table, devicedetails.FieldID, selector),
			sqlgraph.To(deviceiot.Table, deviceiot.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, devicedetails.DeviceiotIDTable, devicedetails.DeviceiotIDColumn),
		)
		fromU = sqlgraph.SetNeighbors(ddq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DeviceDetails entity from the query.
// Returns a *NotFoundError when no DeviceDetails was found.
func (ddq *DeviceDetailsQuery) First(ctx context.Context) (*DeviceDetails, error) {
	nodes, err := ddq.Limit(1).All(setContextOp(ctx, ddq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{devicedetails.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ddq *DeviceDetailsQuery) FirstX(ctx context.Context) *DeviceDetails {
	node, err := ddq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DeviceDetails Id from the query.
// Returns a *NotFoundError when no DeviceDetails Id was found.
func (ddq *DeviceDetailsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ddq.Limit(1).IDs(setContextOp(ctx, ddq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{devicedetails.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ddq *DeviceDetailsQuery) FirstIDX(ctx context.Context) int {
	id, err := ddq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DeviceDetails entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DeviceDetails entity is found.
// Returns a *NotFoundError when no DeviceDetails entities are found.
func (ddq *DeviceDetailsQuery) Only(ctx context.Context) (*DeviceDetails, error) {
	nodes, err := ddq.Limit(2).All(setContextOp(ctx, ddq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{devicedetails.Label}
	default:
		return nil, &NotSingularError{devicedetails.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ddq *DeviceDetailsQuery) OnlyX(ctx context.Context) *DeviceDetails {
	node, err := ddq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DeviceDetails Id in the query.
// Returns a *NotSingularError when more than one DeviceDetails Id is found.
// Returns a *NotFoundError when no entities are found.
func (ddq *DeviceDetailsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ddq.Limit(2).IDs(setContextOp(ctx, ddq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{devicedetails.Label}
	default:
		err = &NotSingularError{devicedetails.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ddq *DeviceDetailsQuery) OnlyIDX(ctx context.Context) int {
	id, err := ddq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DeviceDetailsSlice.
func (ddq *DeviceDetailsQuery) All(ctx context.Context) ([]*DeviceDetails, error) {
	ctx = setContextOp(ctx, ddq.ctx, "All")
	if err := ddq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DeviceDetails, *DeviceDetailsQuery]()
	return withInterceptors[[]*DeviceDetails](ctx, ddq, qr, ddq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ddq *DeviceDetailsQuery) AllX(ctx context.Context) []*DeviceDetails {
	nodes, err := ddq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DeviceDetails IDs.
func (ddq *DeviceDetailsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ddq.ctx.Unique == nil && ddq.path != nil {
		ddq.Unique(true)
	}
	ctx = setContextOp(ctx, ddq.ctx, "IDs")
	if err = ddq.Select(devicedetails.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ddq *DeviceDetailsQuery) IDsX(ctx context.Context) []int {
	ids, err := ddq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ddq *DeviceDetailsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ddq.ctx, "Count")
	if err := ddq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ddq, querierCount[*DeviceDetailsQuery](), ddq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ddq *DeviceDetailsQuery) CountX(ctx context.Context) int {
	count, err := ddq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ddq *DeviceDetailsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ddq.ctx, "Exist")
	switch _, err := ddq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ddq *DeviceDetailsQuery) ExistX(ctx context.Context) bool {
	exist, err := ddq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeviceDetailsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ddq *DeviceDetailsQuery) Clone() *DeviceDetailsQuery {
	if ddq == nil {
		return nil
	}
	return &DeviceDetailsQuery{
		config:          ddq.config,
		ctx:             ddq.ctx.Clone(),
		order:           append([]devicedetails.OrderOption{}, ddq.order...),
		inters:          append([]Interceptor{}, ddq.inters...),
		predicates:      append([]predicate.DeviceDetails{}, ddq.predicates...),
		withDeviceiotID: ddq.withDeviceiotID.Clone(),
		// clone intermediate query.
		sql:  ddq.sql.Clone(),
		path: ddq.path,
	}
}

// WithDeviceiotID tells the query-builder to eager-load the nodes that are connected to
// the "deviceiot_id" edge. The optional arguments are used to configure the query builder of the edge.
func (ddq *DeviceDetailsQuery) WithDeviceiotID(opts ...func(*DeviceIotQuery)) *DeviceDetailsQuery {
	query := (&DeviceIotClient{config: ddq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ddq.withDeviceiotID = query
	return ddq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		LightStatus bool `json:"light_status,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DeviceDetails.Query().
//		GroupBy(devicedetails.FieldLightStatus).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ddq *DeviceDetailsQuery) GroupBy(field string, fields ...string) *DeviceDetailsGroupBy {
	ddq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DeviceDetailsGroupBy{build: ddq}
	grbuild.flds = &ddq.ctx.Fields
	grbuild.label = devicedetails.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		LightStatus bool `json:"light_status,omitempty"`
//	}
//
//	client.DeviceDetails.Query().
//		Select(devicedetails.FieldLightStatus).
//		Scan(ctx, &v)
func (ddq *DeviceDetailsQuery) Select(fields ...string) *DeviceDetailsSelect {
	ddq.ctx.Fields = append(ddq.ctx.Fields, fields...)
	sbuild := &DeviceDetailsSelect{DeviceDetailsQuery: ddq}
	sbuild.label = devicedetails.Label
	sbuild.flds, sbuild.scan = &ddq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DeviceDetailsSelect configured with the given aggregations.
func (ddq *DeviceDetailsQuery) Aggregate(fns ...AggregateFunc) *DeviceDetailsSelect {
	return ddq.Select().Aggregate(fns...)
}

func (ddq *DeviceDetailsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ddq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ddq); err != nil {
				return err
			}
		}
	}
	for _, f := range ddq.ctx.Fields {
		if !devicedetails.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ddq.path != nil {
		prev, err := ddq.path(ctx)
		if err != nil {
			return err
		}
		ddq.sql = prev
	}
	return nil
}

func (ddq *DeviceDetailsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DeviceDetails, error) {
	var (
		nodes       = []*DeviceDetails{}
		withFKs     = ddq.withFKs
		_spec       = ddq.querySpec()
		loadedTypes = [1]bool{
			ddq.withDeviceiotID != nil,
		}
	)
	if ddq.withDeviceiotID != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, devicedetails.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DeviceDetails).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DeviceDetails{config: ddq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ddq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ddq.withDeviceiotID; query != nil {
		if err := ddq.loadDeviceiotID(ctx, query, nodes, nil,
			func(n *DeviceDetails, e *DeviceIot) { n.Edges.DeviceiotID = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ddq *DeviceDetailsQuery) loadDeviceiotID(ctx context.Context, query *DeviceIotQuery, nodes []*DeviceDetails, init func(*DeviceDetails), assign func(*DeviceDetails, *DeviceIot)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*DeviceDetails)
	for i := range nodes {
		if nodes[i].device_iot_devicedetails == nil {
			continue
		}
		fk := *nodes[i].device_iot_devicedetails
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(deviceiot.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "device_iot_devicedetails" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ddq *DeviceDetailsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ddq.querySpec()
	_spec.Node.Columns = ddq.ctx.Fields
	if len(ddq.ctx.Fields) > 0 {
		_spec.Unique = ddq.ctx.Unique != nil && *ddq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ddq.driver, _spec)
}

func (ddq *DeviceDetailsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(devicedetails.Table, devicedetails.Columns, sqlgraph.NewFieldSpec(devicedetails.FieldID, field.TypeInt))
	_spec.From = ddq.sql
	if unique := ddq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ddq.path != nil {
		_spec.Unique = true
	}
	if fields := ddq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, devicedetails.FieldID)
		for i := range fields {
			if fields[i] != devicedetails.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ddq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ddq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ddq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ddq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ddq *DeviceDetailsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ddq.driver.Dialect())
	t1 := builder.Table(devicedetails.Table)
	columns := ddq.ctx.Fields
	if len(columns) == 0 {
		columns = devicedetails.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ddq.sql != nil {
		selector = ddq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ddq.ctx.Unique != nil && *ddq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ddq.predicates {
		p(selector)
	}
	for _, p := range ddq.order {
		p(selector)
	}
	if offset := ddq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ddq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DeviceDetailsGroupBy is the group-by builder for DeviceDetails entities.
type DeviceDetailsGroupBy struct {
	selector
	build *DeviceDetailsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ddgb *DeviceDetailsGroupBy) Aggregate(fns ...AggregateFunc) *DeviceDetailsGroupBy {
	ddgb.fns = append(ddgb.fns, fns...)
	return ddgb
}

// Scan applies the selector query and scans the result into the given value.
func (ddgb *DeviceDetailsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ddgb.build.ctx, "GroupBy")
	if err := ddgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeviceDetailsQuery, *DeviceDetailsGroupBy](ctx, ddgb.build, ddgb, ddgb.build.inters, v)
}

func (ddgb *DeviceDetailsGroupBy) sqlScan(ctx context.Context, root *DeviceDetailsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ddgb.fns))
	for _, fn := range ddgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ddgb.flds)+len(ddgb.fns))
		for _, f := range *ddgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ddgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ddgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DeviceDetailsSelect is the builder for selecting fields of DeviceDetails entities.
type DeviceDetailsSelect struct {
	*DeviceDetailsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dds *DeviceDetailsSelect) Aggregate(fns ...AggregateFunc) *DeviceDetailsSelect {
	dds.fns = append(dds.fns, fns...)
	return dds
}

// Scan applies the selector query and scans the result into the given value.
func (dds *DeviceDetailsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dds.ctx, "Select")
	if err := dds.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeviceDetailsQuery, *DeviceDetailsSelect](ctx, dds.DeviceDetailsQuery, dds, dds.inters, v)
}

func (dds *DeviceDetailsSelect) sqlScan(ctx context.Context, root *DeviceDetailsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dds.fns))
	for _, fn := range dds.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dds.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dds.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
