// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"siliconvali/ent/devicedetails"
	"siliconvali/ent/deviceiot"
	"siliconvali/ent/mainiot"
	"siliconvali/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DeviceIotQuery is the builder for querying DeviceIot entities.
type DeviceIotQuery struct {
	config
	ctx               *QueryContext
	order             []deviceiot.OrderOption
	inters            []Interceptor
	predicates        []predicate.DeviceIot
	withMainiotID     *MainIotQuery
	withDevicedetails *DeviceDetailsQuery
	withFKs           bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DeviceIotQuery builder.
func (diq *DeviceIotQuery) Where(ps ...predicate.DeviceIot) *DeviceIotQuery {
	diq.predicates = append(diq.predicates, ps...)
	return diq
}

// Limit the number of records to be returned by this query.
func (diq *DeviceIotQuery) Limit(limit int) *DeviceIotQuery {
	diq.ctx.Limit = &limit
	return diq
}

// Offset to start from.
func (diq *DeviceIotQuery) Offset(offset int) *DeviceIotQuery {
	diq.ctx.Offset = &offset
	return diq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (diq *DeviceIotQuery) Unique(unique bool) *DeviceIotQuery {
	diq.ctx.Unique = &unique
	return diq
}

// Order specifies how the records should be ordered.
func (diq *DeviceIotQuery) Order(o ...deviceiot.OrderOption) *DeviceIotQuery {
	diq.order = append(diq.order, o...)
	return diq
}

// QueryMainiotID chains the current query on the "mainiot_id" edge.
func (diq *DeviceIotQuery) QueryMainiotID() *MainIotQuery {
	query := (&MainIotClient{config: diq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := diq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := diq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deviceiot.Table, deviceiot.FieldID, selector),
			sqlgraph.To(mainiot.Table, mainiot.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, deviceiot.MainiotIDTable, deviceiot.MainiotIDColumn),
		)
		fromU = sqlgraph.SetNeighbors(diq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDevicedetails chains the current query on the "devicedetails" edge.
func (diq *DeviceIotQuery) QueryDevicedetails() *DeviceDetailsQuery {
	query := (&DeviceDetailsClient{config: diq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := diq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := diq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(deviceiot.Table, deviceiot.FieldID, selector),
			sqlgraph.To(devicedetails.Table, devicedetails.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, deviceiot.DevicedetailsTable, deviceiot.DevicedetailsColumn),
		)
		fromU = sqlgraph.SetNeighbors(diq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DeviceIot entity from the query.
// Returns a *NotFoundError when no DeviceIot was found.
func (diq *DeviceIotQuery) First(ctx context.Context) (*DeviceIot, error) {
	nodes, err := diq.Limit(1).All(setContextOp(ctx, diq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{deviceiot.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (diq *DeviceIotQuery) FirstX(ctx context.Context) *DeviceIot {
	node, err := diq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DeviceIot Id from the query.
// Returns a *NotFoundError when no DeviceIot Id was found.
func (diq *DeviceIotQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = diq.Limit(1).IDs(setContextOp(ctx, diq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{deviceiot.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (diq *DeviceIotQuery) FirstIDX(ctx context.Context) int64 {
	id, err := diq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DeviceIot entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DeviceIot entity is found.
// Returns a *NotFoundError when no DeviceIot entities are found.
func (diq *DeviceIotQuery) Only(ctx context.Context) (*DeviceIot, error) {
	nodes, err := diq.Limit(2).All(setContextOp(ctx, diq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{deviceiot.Label}
	default:
		return nil, &NotSingularError{deviceiot.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (diq *DeviceIotQuery) OnlyX(ctx context.Context) *DeviceIot {
	node, err := diq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DeviceIot Id in the query.
// Returns a *NotSingularError when more than one DeviceIot Id is found.
// Returns a *NotFoundError when no entities are found.
func (diq *DeviceIotQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = diq.Limit(2).IDs(setContextOp(ctx, diq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{deviceiot.Label}
	default:
		err = &NotSingularError{deviceiot.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (diq *DeviceIotQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := diq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DeviceIots.
func (diq *DeviceIotQuery) All(ctx context.Context) ([]*DeviceIot, error) {
	ctx = setContextOp(ctx, diq.ctx, "All")
	if err := diq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DeviceIot, *DeviceIotQuery]()
	return withInterceptors[[]*DeviceIot](ctx, diq, qr, diq.inters)
}

// AllX is like All, but panics if an error occurs.
func (diq *DeviceIotQuery) AllX(ctx context.Context) []*DeviceIot {
	nodes, err := diq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DeviceIot IDs.
func (diq *DeviceIotQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if diq.ctx.Unique == nil && diq.path != nil {
		diq.Unique(true)
	}
	ctx = setContextOp(ctx, diq.ctx, "IDs")
	if err = diq.Select(deviceiot.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (diq *DeviceIotQuery) IDsX(ctx context.Context) []int64 {
	ids, err := diq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (diq *DeviceIotQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, diq.ctx, "Count")
	if err := diq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, diq, querierCount[*DeviceIotQuery](), diq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (diq *DeviceIotQuery) CountX(ctx context.Context) int {
	count, err := diq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (diq *DeviceIotQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, diq.ctx, "Exist")
	switch _, err := diq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (diq *DeviceIotQuery) ExistX(ctx context.Context) bool {
	exist, err := diq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DeviceIotQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (diq *DeviceIotQuery) Clone() *DeviceIotQuery {
	if diq == nil {
		return nil
	}
	return &DeviceIotQuery{
		config:            diq.config,
		ctx:               diq.ctx.Clone(),
		order:             append([]deviceiot.OrderOption{}, diq.order...),
		inters:            append([]Interceptor{}, diq.inters...),
		predicates:        append([]predicate.DeviceIot{}, diq.predicates...),
		withMainiotID:     diq.withMainiotID.Clone(),
		withDevicedetails: diq.withDevicedetails.Clone(),
		// clone intermediate query.
		sql:  diq.sql.Clone(),
		path: diq.path,
	}
}

// WithMainiotID tells the query-builder to eager-load the nodes that are connected to
// the "mainiot_id" edge. The optional arguments are used to configure the query builder of the edge.
func (diq *DeviceIotQuery) WithMainiotID(opts ...func(*MainIotQuery)) *DeviceIotQuery {
	query := (&MainIotClient{config: diq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	diq.withMainiotID = query
	return diq
}

// WithDevicedetails tells the query-builder to eager-load the nodes that are connected to
// the "devicedetails" edge. The optional arguments are used to configure the query builder of the edge.
func (diq *DeviceIotQuery) WithDevicedetails(opts ...func(*DeviceDetailsQuery)) *DeviceIotQuery {
	query := (&DeviceDetailsClient{config: diq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	diq.withDevicedetails = query
	return diq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		DisplayName string `json:"display_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DeviceIot.Query().
//		GroupBy(deviceiot.FieldDisplayName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (diq *DeviceIotQuery) GroupBy(field string, fields ...string) *DeviceIotGroupBy {
	diq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DeviceIotGroupBy{build: diq}
	grbuild.flds = &diq.ctx.Fields
	grbuild.label = deviceiot.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		DisplayName string `json:"display_name,omitempty"`
//	}
//
//	client.DeviceIot.Query().
//		Select(deviceiot.FieldDisplayName).
//		Scan(ctx, &v)
func (diq *DeviceIotQuery) Select(fields ...string) *DeviceIotSelect {
	diq.ctx.Fields = append(diq.ctx.Fields, fields...)
	sbuild := &DeviceIotSelect{DeviceIotQuery: diq}
	sbuild.label = deviceiot.Label
	sbuild.flds, sbuild.scan = &diq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DeviceIotSelect configured with the given aggregations.
func (diq *DeviceIotQuery) Aggregate(fns ...AggregateFunc) *DeviceIotSelect {
	return diq.Select().Aggregate(fns...)
}

func (diq *DeviceIotQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range diq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, diq); err != nil {
				return err
			}
		}
	}
	for _, f := range diq.ctx.Fields {
		if !deviceiot.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if diq.path != nil {
		prev, err := diq.path(ctx)
		if err != nil {
			return err
		}
		diq.sql = prev
	}
	return nil
}

func (diq *DeviceIotQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DeviceIot, error) {
	var (
		nodes       = []*DeviceIot{}
		withFKs     = diq.withFKs
		_spec       = diq.querySpec()
		loadedTypes = [2]bool{
			diq.withMainiotID != nil,
			diq.withDevicedetails != nil,
		}
	)
	if diq.withMainiotID != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, deviceiot.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DeviceIot).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DeviceIot{config: diq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, diq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := diq.withMainiotID; query != nil {
		if err := diq.loadMainiotID(ctx, query, nodes, nil,
			func(n *DeviceIot, e *MainIot) { n.Edges.MainiotID = e }); err != nil {
			return nil, err
		}
	}
	if query := diq.withDevicedetails; query != nil {
		if err := diq.loadDevicedetails(ctx, query, nodes,
			func(n *DeviceIot) { n.Edges.Devicedetails = []*DeviceDetails{} },
			func(n *DeviceIot, e *DeviceDetails) { n.Edges.Devicedetails = append(n.Edges.Devicedetails, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (diq *DeviceIotQuery) loadMainiotID(ctx context.Context, query *MainIotQuery, nodes []*DeviceIot, init func(*DeviceIot), assign func(*DeviceIot, *MainIot)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*DeviceIot)
	for i := range nodes {
		if nodes[i].main_iot_deviceiots == nil {
			continue
		}
		fk := *nodes[i].main_iot_deviceiots
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(mainiot.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "main_iot_deviceiots" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (diq *DeviceIotQuery) loadDevicedetails(ctx context.Context, query *DeviceDetailsQuery, nodes []*DeviceIot, init func(*DeviceIot), assign func(*DeviceIot, *DeviceDetails)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int64]*DeviceIot)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.DeviceDetails(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(deviceiot.DevicedetailsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.device_iot_devicedetails
		if fk == nil {
			return fmt.Errorf(`foreign-key "device_iot_devicedetails" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "device_iot_devicedetails" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (diq *DeviceIotQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := diq.querySpec()
	_spec.Node.Columns = diq.ctx.Fields
	if len(diq.ctx.Fields) > 0 {
		_spec.Unique = diq.ctx.Unique != nil && *diq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, diq.driver, _spec)
}

func (diq *DeviceIotQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(deviceiot.Table, deviceiot.Columns, sqlgraph.NewFieldSpec(deviceiot.FieldID, field.TypeInt64))
	_spec.From = diq.sql
	if unique := diq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if diq.path != nil {
		_spec.Unique = true
	}
	if fields := diq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deviceiot.FieldID)
		for i := range fields {
			if fields[i] != deviceiot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := diq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := diq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := diq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := diq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (diq *DeviceIotQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(diq.driver.Dialect())
	t1 := builder.Table(deviceiot.Table)
	columns := diq.ctx.Fields
	if len(columns) == 0 {
		columns = deviceiot.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if diq.sql != nil {
		selector = diq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if diq.ctx.Unique != nil && *diq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range diq.predicates {
		p(selector)
	}
	for _, p := range diq.order {
		p(selector)
	}
	if offset := diq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := diq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DeviceIotGroupBy is the group-by builder for DeviceIot entities.
type DeviceIotGroupBy struct {
	selector
	build *DeviceIotQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (digb *DeviceIotGroupBy) Aggregate(fns ...AggregateFunc) *DeviceIotGroupBy {
	digb.fns = append(digb.fns, fns...)
	return digb
}

// Scan applies the selector query and scans the result into the given value.
func (digb *DeviceIotGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, digb.build.ctx, "GroupBy")
	if err := digb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeviceIotQuery, *DeviceIotGroupBy](ctx, digb.build, digb, digb.build.inters, v)
}

func (digb *DeviceIotGroupBy) sqlScan(ctx context.Context, root *DeviceIotQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(digb.fns))
	for _, fn := range digb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*digb.flds)+len(digb.fns))
		for _, f := range *digb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*digb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := digb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DeviceIotSelect is the builder for selecting fields of DeviceIot entities.
type DeviceIotSelect struct {
	*DeviceIotQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dis *DeviceIotSelect) Aggregate(fns ...AggregateFunc) *DeviceIotSelect {
	dis.fns = append(dis.fns, fns...)
	return dis
}

// Scan applies the selector query and scans the result into the given value.
func (dis *DeviceIotSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dis.ctx, "Select")
	if err := dis.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DeviceIotQuery, *DeviceIotSelect](ctx, dis.DeviceIotQuery, dis, dis.inters, v)
}

func (dis *DeviceIotSelect) sqlScan(ctx context.Context, root *DeviceIotQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dis.fns))
	for _, fn := range dis.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dis.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dis.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
