// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"siliconvali/ent/mainiot"
	"siliconvali/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MainIotDelete is the builder for deleting a MainIot entity.
type MainIotDelete struct {
	config
	hooks    []Hook
	mutation *MainIotMutation
}

// Where appends a list predicates to the MainIotDelete builder.
func (mid *MainIotDelete) Where(ps ...predicate.MainIot) *MainIotDelete {
	mid.mutation.Where(ps...)
	return mid
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mid *MainIotDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mid.sqlExec, mid.mutation, mid.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mid *MainIotDelete) ExecX(ctx context.Context) int {
	n, err := mid.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mid *MainIotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(mainiot.Table, sqlgraph.NewFieldSpec(mainiot.FieldID, field.TypeInt64))
	if ps := mid.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mid.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mid.mutation.done = true
	return affected, err
}

// MainIotDeleteOne is the builder for deleting a single MainIot entity.
type MainIotDeleteOne struct {
	mid *MainIotDelete
}

// Where appends a list predicates to the MainIotDelete builder.
func (mido *MainIotDeleteOne) Where(ps ...predicate.MainIot) *MainIotDeleteOne {
	mido.mid.mutation.Where(ps...)
	return mido
}

// Exec executes the deletion query.
func (mido *MainIotDeleteOne) Exec(ctx context.Context) error {
	n, err := mido.mid.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{mainiot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mido *MainIotDeleteOne) ExecX(ctx context.Context) {
	if err := mido.Exec(ctx); err != nil {
		panic(err)
	}
}
