// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"siliconvali/ent/plan"
	"siliconvali/ent/predicate"
	"siliconvali/ent/userpaymentplan"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PlanUpdate is the builder for updating Plan entities.
type PlanUpdate struct {
	config
	hooks    []Hook
	mutation *PlanMutation
}

// Where appends a list predicates to the PlanUpdate builder.
func (pu *PlanUpdate) Where(ps ...predicate.Plan) *PlanUpdate {
	pu.mutation.Where(ps...)
	return pu
}

// SetName sets the "name" field.
func (pu *PlanUpdate) SetName(s string) *PlanUpdate {
	pu.mutation.SetName(s)
	return pu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pu *PlanUpdate) SetNillableName(s *string) *PlanUpdate {
	if s != nil {
		pu.SetName(*s)
	}
	return pu
}

// SetPrice sets the "price" field.
func (pu *PlanUpdate) SetPrice(i int64) *PlanUpdate {
	pu.mutation.ResetPrice()
	pu.mutation.SetPrice(i)
	return pu
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (pu *PlanUpdate) SetNillablePrice(i *int64) *PlanUpdate {
	if i != nil {
		pu.SetPrice(*i)
	}
	return pu
}

// AddPrice adds i to the "price" field.
func (pu *PlanUpdate) AddPrice(i int64) *PlanUpdate {
	pu.mutation.AddPrice(i)
	return pu
}

// ClearPrice clears the value of the "price" field.
func (pu *PlanUpdate) ClearPrice() *PlanUpdate {
	pu.mutation.ClearPrice()
	return pu
}

// SetPeriod sets the "period" field.
func (pu *PlanUpdate) SetPeriod(i int) *PlanUpdate {
	pu.mutation.ResetPeriod()
	pu.mutation.SetPeriod(i)
	return pu
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (pu *PlanUpdate) SetNillablePeriod(i *int) *PlanUpdate {
	if i != nil {
		pu.SetPeriod(*i)
	}
	return pu
}

// AddPeriod adds i to the "period" field.
func (pu *PlanUpdate) AddPeriod(i int) *PlanUpdate {
	pu.mutation.AddPeriod(i)
	return pu
}

// ClearPeriod clears the value of the "period" field.
func (pu *PlanUpdate) ClearPeriod() *PlanUpdate {
	pu.mutation.ClearPeriod()
	return pu
}

// SetActive sets the "active" field.
func (pu *PlanUpdate) SetActive(b bool) *PlanUpdate {
	pu.mutation.SetActive(b)
	return pu
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (pu *PlanUpdate) SetNillableActive(b *bool) *PlanUpdate {
	if b != nil {
		pu.SetActive(*b)
	}
	return pu
}

// SetDescription sets the "description" field.
func (pu *PlanUpdate) SetDescription(s string) *PlanUpdate {
	pu.mutation.SetDescription(s)
	return pu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (pu *PlanUpdate) SetNillableDescription(s *string) *PlanUpdate {
	if s != nil {
		pu.SetDescription(*s)
	}
	return pu
}

// ClearDescription clears the value of the "description" field.
func (pu *PlanUpdate) ClearDescription() *PlanUpdate {
	pu.mutation.ClearDescription()
	return pu
}

// AddUserpaymentplanIDs adds the "userpaymentplans" edge to the UserPaymentPlan entity by IDs.
func (pu *PlanUpdate) AddUserpaymentplanIDs(ids ...int64) *PlanUpdate {
	pu.mutation.AddUserpaymentplanIDs(ids...)
	return pu
}

// AddUserpaymentplans adds the "userpaymentplans" edges to the UserPaymentPlan entity.
func (pu *PlanUpdate) AddUserpaymentplans(u ...*UserPaymentPlan) *PlanUpdate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return pu.AddUserpaymentplanIDs(ids...)
}

// Mutation returns the PlanMutation object of the builder.
func (pu *PlanUpdate) Mutation() *PlanMutation {
	return pu.mutation
}

// ClearUserpaymentplans clears all "userpaymentplans" edges to the UserPaymentPlan entity.
func (pu *PlanUpdate) ClearUserpaymentplans() *PlanUpdate {
	pu.mutation.ClearUserpaymentplans()
	return pu
}

// RemoveUserpaymentplanIDs removes the "userpaymentplans" edge to UserPaymentPlan entities by IDs.
func (pu *PlanUpdate) RemoveUserpaymentplanIDs(ids ...int64) *PlanUpdate {
	pu.mutation.RemoveUserpaymentplanIDs(ids...)
	return pu
}

// RemoveUserpaymentplans removes "userpaymentplans" edges to UserPaymentPlan entities.
func (pu *PlanUpdate) RemoveUserpaymentplans(u ...*UserPaymentPlan) *PlanUpdate {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return pu.RemoveUserpaymentplanIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pu *PlanUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pu.sqlSave, pu.mutation, pu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pu *PlanUpdate) SaveX(ctx context.Context) int {
	affected, err := pu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pu *PlanUpdate) Exec(ctx context.Context) error {
	_, err := pu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pu *PlanUpdate) ExecX(ctx context.Context) {
	if err := pu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pu *PlanUpdate) check() error {
	if v, ok := pu.mutation.Name(); ok {
		if err := plan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Plan.name": %w`, err)}
		}
	}
	if v, ok := pu.mutation.Description(); ok {
		if err := plan.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Plan.description": %w`, err)}
		}
	}
	return nil
}

func (pu *PlanUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(plan.Table, plan.Columns, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt))
	if ps := pu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pu.mutation.Name(); ok {
		_spec.SetField(plan.FieldName, field.TypeString, value)
	}
	if value, ok := pu.mutation.Price(); ok {
		_spec.SetField(plan.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := pu.mutation.AddedPrice(); ok {
		_spec.AddField(plan.FieldPrice, field.TypeInt64, value)
	}
	if pu.mutation.PriceCleared() {
		_spec.ClearField(plan.FieldPrice, field.TypeInt64)
	}
	if value, ok := pu.mutation.Period(); ok {
		_spec.SetField(plan.FieldPeriod, field.TypeInt, value)
	}
	if value, ok := pu.mutation.AddedPeriod(); ok {
		_spec.AddField(plan.FieldPeriod, field.TypeInt, value)
	}
	if pu.mutation.PeriodCleared() {
		_spec.ClearField(plan.FieldPeriod, field.TypeInt)
	}
	if value, ok := pu.mutation.Active(); ok {
		_spec.SetField(plan.FieldActive, field.TypeBool, value)
	}
	if value, ok := pu.mutation.Description(); ok {
		_spec.SetField(plan.FieldDescription, field.TypeString, value)
	}
	if pu.mutation.DescriptionCleared() {
		_spec.ClearField(plan.FieldDescription, field.TypeString)
	}
	if pu.mutation.UserpaymentplansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.UserpaymentplansTable,
			Columns: []string{plan.UserpaymentplansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userpaymentplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.RemovedUserpaymentplansIDs(); len(nodes) > 0 && !pu.mutation.UserpaymentplansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.UserpaymentplansTable,
			Columns: []string{plan.UserpaymentplansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userpaymentplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pu.mutation.UserpaymentplansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.UserpaymentplansTable,
			Columns: []string{plan.UserpaymentplansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userpaymentplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, pu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pu.mutation.done = true
	return n, nil
}

// PlanUpdateOne is the builder for updating a single Plan entity.
type PlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlanMutation
}

// SetName sets the "name" field.
func (puo *PlanUpdateOne) SetName(s string) *PlanUpdateOne {
	puo.mutation.SetName(s)
	return puo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (puo *PlanUpdateOne) SetNillableName(s *string) *PlanUpdateOne {
	if s != nil {
		puo.SetName(*s)
	}
	return puo
}

// SetPrice sets the "price" field.
func (puo *PlanUpdateOne) SetPrice(i int64) *PlanUpdateOne {
	puo.mutation.ResetPrice()
	puo.mutation.SetPrice(i)
	return puo
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (puo *PlanUpdateOne) SetNillablePrice(i *int64) *PlanUpdateOne {
	if i != nil {
		puo.SetPrice(*i)
	}
	return puo
}

// AddPrice adds i to the "price" field.
func (puo *PlanUpdateOne) AddPrice(i int64) *PlanUpdateOne {
	puo.mutation.AddPrice(i)
	return puo
}

// ClearPrice clears the value of the "price" field.
func (puo *PlanUpdateOne) ClearPrice() *PlanUpdateOne {
	puo.mutation.ClearPrice()
	return puo
}

// SetPeriod sets the "period" field.
func (puo *PlanUpdateOne) SetPeriod(i int) *PlanUpdateOne {
	puo.mutation.ResetPeriod()
	puo.mutation.SetPeriod(i)
	return puo
}

// SetNillablePeriod sets the "period" field if the given value is not nil.
func (puo *PlanUpdateOne) SetNillablePeriod(i *int) *PlanUpdateOne {
	if i != nil {
		puo.SetPeriod(*i)
	}
	return puo
}

// AddPeriod adds i to the "period" field.
func (puo *PlanUpdateOne) AddPeriod(i int) *PlanUpdateOne {
	puo.mutation.AddPeriod(i)
	return puo
}

// ClearPeriod clears the value of the "period" field.
func (puo *PlanUpdateOne) ClearPeriod() *PlanUpdateOne {
	puo.mutation.ClearPeriod()
	return puo
}

// SetActive sets the "active" field.
func (puo *PlanUpdateOne) SetActive(b bool) *PlanUpdateOne {
	puo.mutation.SetActive(b)
	return puo
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (puo *PlanUpdateOne) SetNillableActive(b *bool) *PlanUpdateOne {
	if b != nil {
		puo.SetActive(*b)
	}
	return puo
}

// SetDescription sets the "description" field.
func (puo *PlanUpdateOne) SetDescription(s string) *PlanUpdateOne {
	puo.mutation.SetDescription(s)
	return puo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (puo *PlanUpdateOne) SetNillableDescription(s *string) *PlanUpdateOne {
	if s != nil {
		puo.SetDescription(*s)
	}
	return puo
}

// ClearDescription clears the value of the "description" field.
func (puo *PlanUpdateOne) ClearDescription() *PlanUpdateOne {
	puo.mutation.ClearDescription()
	return puo
}

// AddUserpaymentplanIDs adds the "userpaymentplans" edge to the UserPaymentPlan entity by IDs.
func (puo *PlanUpdateOne) AddUserpaymentplanIDs(ids ...int64) *PlanUpdateOne {
	puo.mutation.AddUserpaymentplanIDs(ids...)
	return puo
}

// AddUserpaymentplans adds the "userpaymentplans" edges to the UserPaymentPlan entity.
func (puo *PlanUpdateOne) AddUserpaymentplans(u ...*UserPaymentPlan) *PlanUpdateOne {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return puo.AddUserpaymentplanIDs(ids...)
}

// Mutation returns the PlanMutation object of the builder.
func (puo *PlanUpdateOne) Mutation() *PlanMutation {
	return puo.mutation
}

// ClearUserpaymentplans clears all "userpaymentplans" edges to the UserPaymentPlan entity.
func (puo *PlanUpdateOne) ClearUserpaymentplans() *PlanUpdateOne {
	puo.mutation.ClearUserpaymentplans()
	return puo
}

// RemoveUserpaymentplanIDs removes the "userpaymentplans" edge to UserPaymentPlan entities by IDs.
func (puo *PlanUpdateOne) RemoveUserpaymentplanIDs(ids ...int64) *PlanUpdateOne {
	puo.mutation.RemoveUserpaymentplanIDs(ids...)
	return puo
}

// RemoveUserpaymentplans removes "userpaymentplans" edges to UserPaymentPlan entities.
func (puo *PlanUpdateOne) RemoveUserpaymentplans(u ...*UserPaymentPlan) *PlanUpdateOne {
	ids := make([]int64, len(u))
	for i := range u {
		ids[i] = u[i].ID
	}
	return puo.RemoveUserpaymentplanIDs(ids...)
}

// Where appends a list predicates to the PlanUpdate builder.
func (puo *PlanUpdateOne) Where(ps ...predicate.Plan) *PlanUpdateOne {
	puo.mutation.Where(ps...)
	return puo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (puo *PlanUpdateOne) Select(field string, fields ...string) *PlanUpdateOne {
	puo.fields = append([]string{field}, fields...)
	return puo
}

// Save executes the query and returns the updated Plan entity.
func (puo *PlanUpdateOne) Save(ctx context.Context) (*Plan, error) {
	return withHooks(ctx, puo.sqlSave, puo.mutation, puo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (puo *PlanUpdateOne) SaveX(ctx context.Context) *Plan {
	node, err := puo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (puo *PlanUpdateOne) Exec(ctx context.Context) error {
	_, err := puo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (puo *PlanUpdateOne) ExecX(ctx context.Context) {
	if err := puo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (puo *PlanUpdateOne) check() error {
	if v, ok := puo.mutation.Name(); ok {
		if err := plan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Plan.name": %w`, err)}
		}
	}
	if v, ok := puo.mutation.Description(); ok {
		if err := plan.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Plan.description": %w`, err)}
		}
	}
	return nil
}

func (puo *PlanUpdateOne) sqlSave(ctx context.Context) (_node *Plan, err error) {
	if err := puo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plan.Table, plan.Columns, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeInt))
	id, ok := puo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Plan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := puo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, plan.FieldID)
		for _, f := range fields {
			if !plan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != plan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := puo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := puo.mutation.Name(); ok {
		_spec.SetField(plan.FieldName, field.TypeString, value)
	}
	if value, ok := puo.mutation.Price(); ok {
		_spec.SetField(plan.FieldPrice, field.TypeInt64, value)
	}
	if value, ok := puo.mutation.AddedPrice(); ok {
		_spec.AddField(plan.FieldPrice, field.TypeInt64, value)
	}
	if puo.mutation.PriceCleared() {
		_spec.ClearField(plan.FieldPrice, field.TypeInt64)
	}
	if value, ok := puo.mutation.Period(); ok {
		_spec.SetField(plan.FieldPeriod, field.TypeInt, value)
	}
	if value, ok := puo.mutation.AddedPeriod(); ok {
		_spec.AddField(plan.FieldPeriod, field.TypeInt, value)
	}
	if puo.mutation.PeriodCleared() {
		_spec.ClearField(plan.FieldPeriod, field.TypeInt)
	}
	if value, ok := puo.mutation.Active(); ok {
		_spec.SetField(plan.FieldActive, field.TypeBool, value)
	}
	if value, ok := puo.mutation.Description(); ok {
		_spec.SetField(plan.FieldDescription, field.TypeString, value)
	}
	if puo.mutation.DescriptionCleared() {
		_spec.ClearField(plan.FieldDescription, field.TypeString)
	}
	if puo.mutation.UserpaymentplansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.UserpaymentplansTable,
			Columns: []string{plan.UserpaymentplansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userpaymentplan.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.RemovedUserpaymentplansIDs(); len(nodes) > 0 && !puo.mutation.UserpaymentplansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.UserpaymentplansTable,
			Columns: []string{plan.UserpaymentplansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userpaymentplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := puo.mutation.UserpaymentplansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.UserpaymentplansTable,
			Columns: []string{plan.UserpaymentplansColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(userpaymentplan.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Plan{config: puo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, puo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	puo.mutation.done = true
	return _node, nil
}
