// Code generated by ent, DO NOT EDIT.

package devicedetails

import (
	"siliconvali/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.DeviceDetails {
	return predicate.DeviceDetails(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.DeviceDetails {
	return predicate.DeviceDetails(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.DeviceDetails {
	return predicate.DeviceDetails(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.DeviceDetails {
	return predicate.DeviceDetails(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.DeviceDetails {
	return predicate.DeviceDetails(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.DeviceDetails {
	return predicate.DeviceDetails(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.DeviceDetails {
	return predicate.DeviceDetails(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.DeviceDetails {
	return predicate.DeviceDetails(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.DeviceDetails {
	return predicate.DeviceDetails(sql.FieldLTE(FieldID, id))
}

// LightStatus applies equality check predicate on the "light_status" field. It's identical to LightStatusEQ.
func LightStatus(v bool) predicate.DeviceDetails {
	return predicate.DeviceDetails(sql.FieldEQ(FieldLightStatus, v))
}

// LightStatusEQ applies the EQ predicate on the "light_status" field.
func LightStatusEQ(v bool) predicate.DeviceDetails {
	return predicate.DeviceDetails(sql.FieldEQ(FieldLightStatus, v))
}

// LightStatusNEQ applies the NEQ predicate on the "light_status" field.
func LightStatusNEQ(v bool) predicate.DeviceDetails {
	return predicate.DeviceDetails(sql.FieldNEQ(FieldLightStatus, v))
}

// LightStatusIsNil applies the IsNil predicate on the "light_status" field.
func LightStatusIsNil() predicate.DeviceDetails {
	return predicate.DeviceDetails(sql.FieldIsNull(FieldLightStatus))
}

// LightStatusNotNil applies the NotNil predicate on the "light_status" field.
func LightStatusNotNil() predicate.DeviceDetails {
	return predicate.DeviceDetails(sql.FieldNotNull(FieldLightStatus))
}

// HasDeviceiotID applies the HasEdge predicate on the "deviceiot_id" edge.
func HasDeviceiotID() predicate.DeviceDetails {
	return predicate.DeviceDetails(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, DeviceiotIDTable, DeviceiotIDColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeviceiotIDWith applies the HasEdge predicate on the "deviceiot_id" edge with a given conditions (other predicates).
func HasDeviceiotIDWith(preds ...predicate.DeviceIot) predicate.DeviceDetails {
	return predicate.DeviceDetails(func(s *sql.Selector) {
		step := newDeviceiotIDStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DeviceDetails) predicate.DeviceDetails {
	return predicate.DeviceDetails(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DeviceDetails) predicate.DeviceDetails {
	return predicate.DeviceDetails(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DeviceDetails) predicate.DeviceDetails {
	return predicate.DeviceDetails(sql.NotPredicates(p))
}
